package com.moviedb_api.price;


import com.moviedb_api.movie.Movie;
import com.moviedb_api.movie.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/price") // This means URL's start with /movies (after Application path)
public class PriceController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PriceRepository priceRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Price> getAllPrices() {
        // This returns a JSON or XML with the movies
        return priceRepository.findAll();

    }

    @GetMapping("/{id}")
    public @ResponseBody Optional<Price> findPriceById(
            @PathVariable(value = "id") String id)
    {
        return priceRepository.findPriceByMovieId(id);
    }
}