package com.moviedb_api.employee;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;
@Controller // This means that this class is a Controller
@RequestMapping(path="/employee") // This means URL's start with /demo (after Application path)
public class EmployeeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeRepository employeeRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Employee> getAllUsers() {
        // This returns a JSON or XML with the movies
        return employeeRepository.findAll();
    }

    @GetMapping("/{id}")
    public @ResponseBody Optional<Employee> getEmployeeById(@PathVariable(value = "id") Integer id)
    {
        return employeeRepository.findById(id);
    }
}
