package com.moviedb_api.star;
;
import com.fasterxml.jackson.annotation.JsonView;
import com.moviedb_api.Views;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/star") // This means URL's start with /movies (after Application path)
public class StarController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StarRepository starRepository;

    @GetMapping(path="/all")
    @JsonView(Views.Summary.class)
    public @ResponseBody Iterable<Star> getAllStars() {
        // This returns a JSON or XML with the movies
        return starRepository.findAll();
    }

    @GetMapping(path="/name/{name}")
    @JsonView(Views.Summary.class)
    public @ResponseBody Iterable<Star> findStarByName(@PathVariable String name) {
        // This returns a JSON or XML with the movies
        return starRepository.findByName(name);
    }

    @GetMapping("/{id}")
    @JsonView(Views.Summary.class)
    public @ResponseBody Optional<Star> findStarById(
            @PathVariable(value = "id") String id)
    {
        return starRepository.findById(id);
    }
}