package com.moviedb_api.stars_in_movies;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Optional;
import java.util.Set;


//Used for Testing Only. Use /star for db searches

/**
@Controller // This means that this class is a Controller
@RequestMapping(path="/star_movie")
public class Star_MovieController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Star_MovieRepository star_movieRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Star_Movie> getAllStarMovie() {
        // This returns a JSON or XML with the movies
        return star_movieRepository.findAll();
    }

    @GetMapping(path="/movie_id/{id}")
    public @ResponseBody Iterable<Star_Movie> getStarMovieByMovieId(
            @PathVariable(value = "id") String id) {
        // This returns a JSON or XML with the movies
        return star_movieRepository.findByMovieId(id);
    }

    @GetMapping("/star_id/{id}")
    public @ResponseBody Iterable<Star_Movie> getStarMovieByStarId(
            @PathVariable(value = "id") String id) {

       return star_movieRepository.findByStarId(id);
    }
}

 **/