package com.moviedb_api.order;

import com.moviedb_api.sale.Sale;
import com.moviedb_api.sale.SaleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/order") // This means URL's start with /movies (after Application path)
public class OrderController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrderRepository orderRepository;

    @Autowired
    private SaleRepository saleRepository;

    private OrderService orderService;

    @GetMapping("/{id}")
    public @ResponseBody
    ResponseEntity<?> findOrderById(@PathVariable(value = "id") Integer id) {

        OrderRequest orderRequest = new OrderRequest();
        orderRequest.setId(id);
        return orderService.getOrder(orderRequest);
    }

    @PostMapping("/")
    public @ResponseBody
    ResponseEntity<?> updateByOrder(@RequestBody OrderRequest request) {

        return orderService.updateOrder(request);
    }


    @PutMapping("/")
    public @ResponseBody
    ResponseEntity<?> addOrder(@RequestBody OrderRequest request) {

        return orderService.addOrder(request);
    }

    @GetMapping(path="/count/{id}")
    public @ResponseBody
    long getMovieIdCount(
            @PathVariable(value = "id") String id
    ){
        return orderRepository.countByMovieId(id);
    }

    @GetMapping(path="/sellers")
    public @ResponseBody
    Page<Order> getBestSellers(
            @RequestParam Optional<Integer> limit,
            @RequestParam Optional<Integer> page
    ){
        return orderRepository.findBestSellers(
                PageRequest.of(
                        page.orElse(0),
                        limit.orElse(5)
                )
        );
    }

    @GetMapping(path="/all")
    public @ResponseBody
    Page<Order> getAllOrders(
            @RequestParam Optional<Integer> limit,
            @RequestParam Optional<Integer> page,
            @RequestParam Optional<String> sortBy
    )     {
        return orderRepository.findAll(
                PageRequest.of(
                        page.orElse(0),
                        limit.orElse(5),
                        Sort.Direction.ASC, sortBy.orElse("id")
                )
        );
    }


}